services:
  db:
    image: postgis/postgis:17-3.4
    container_name: gis_postgres
    ports:
      - "9002:9002"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemelater
      POSTGRES_DB: appdb

  authentication:
    build:
      context: .
      dockerfile: authentication/Dockerfile
    ports:
      - "${AUTH_SERVER_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - mailhog
    volumes:
      - maven_cache:/root/.m2

  banking:
    build:
      context: .
      dockerfile: banking/Dockerfile
    ports:
      - "${BANKING_SERVER_PORT}:8001"
    env_file:
      - .env
    depends_on:
      - db
      - mailhog
      - redis
      - authentication
    volumes:
      - maven_cache:/root/.m2

  recommendation:
    build:
      context: .
      dockerfile: recommendation/Dockerfile
    ports:
      - "${RECOMMENDATION_SERVER_PORT}:8002"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - authentication
      - banking
    volumes:
      - maven_cache:/root/.m2

  notification:
    build:
      context: .
      dockerfile: notification/Dockerfile
    ports:
      - "${NOTIFICATION_SERVER_PORT}:8003"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - authentication
      - banking
      - recommendation
    volumes:
      - maven_cache:/root/.m2

  minio:
    image: minio/minio@sha256:a1ea29fa28355559ef137d71fc570e508a214ec84ff8083e39bc5428980b015e
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"     # http://localhost:9001/browser
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"    # Web UI at http://localhost:8025
      - "1025:1025"    # SMTP port (your services will send mail to this)
    restart: always


  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"    # Web UI at http://localhost:5540
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  minio_data:
  maven_cache:

