package com.project.common.enums

enum class ErrorCode {
    ACCESS_DENIED,
    INVALID_CREDENTIALS,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    INVALID_INPUT,
    INTERNAL_SERVER_ERROR,
    UNAUTHORIZED,
    EXPIRED_TOKEN,
    ROLE_NOT_FOUND,
    INVALID_TOKEN,
    ACCOUNT_NOT_ACTIVE,
    ACCOUNT_LIMIT_REACHED,
    ACCOUNT_VERIFICATION_EXCEPTION,
    ACCOUNT_NOT_FOUND,
    INVALID_FUNDS,
    INVALID_TRANSFER,
    INVALID_AGE,
    ACCOUNT_NOT_VERIFIED,
    INCOMPLETE_USER_REGISTRATION,
    KYC_NOT_FOUND,
    ACCOUNT_PRODUCT_NOT_FOUND
}